apiVersion: v1
kind: Pod
metadata:
  name: zigbee2mqtt-debug-pod
  namespace: homeassistant
  labels:
    app: zigbee2mqtt
    app.kubernetes.io/instance: zigbee2mqtt
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zigbee2mqtt
    app.kubernetes.io/version: 2.2.1
    helm.sh/chart: zigbee2mqtt-2.2.1
spec:
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: data-volume-zigbee2mqtt-0
    - name: config-volume
      configMap:
        name: zigbee2mqtt
        defaultMode: 420
  containers:
    - name: zigbee2mqtt
      image: koenkk/zigbee2mqtt:2.2.1
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo $(date); sleep 10;done"]
      # Default entry
      # command: "/usr/local/bin/docker-entrypoint.sh"
      # args: ["/sbin/tini", "--", "node index.js"]
      #Console command: #> /usr/local/bin/docker-entrypoint.sh /sbin/tini -- node index.js
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP
      env:
        - name: Z2M_ONBOARD_NO_SERVER
          value: "1"
        - name: TZ
          value: UTC
      resources:
        limits:
          akri.sh/akri-udev-zigbee-dongle: "1"
          cpu: 200m
          memory: 600Mi
        requests:
          akri.sh/akri-udev-zigbee-dongle: "1"
          cpu: 200m
          memory: 600Mi
      volumeMounts:
        - name: config-volume
          mountPath: /app/data/configmap-configuration.yaml
          subPath: configuration.yaml
        - name: data-volume
          mountPath: /app/data/
      imagePullPolicy: IfNotPresent
      securityContext:
        capabilities:
          add:
            # - CAP_SYS_ADMIN
            - SYS_ADMIN
        privileged: true
  # securityContext:
  #   seccompProfile:
  #     type: RuntimeDefault
